disable_methods: false
disable_native_funcs: false
auto_reload: true
force_compile: false
disable_cache: false
force_include: true
auto_escape: false
force_verify: false
disable_php_calls: false
disable_statics: false
strip: true
